services:
  renamer:
    build: .
    container_name: episode-renamer
    restart: unless-stopped
    ports:
      - "3333:3333"
    environment:
      - BASE_PATH=/TV Shows
      - VALID_EXT=[".mp4",".mkv",".avi"]
      - TMDB_API_KEY=e3ee010a10084bde17623ff3f994145a
    volumes:
      - ./dependencies/.env:/app/dependencies/.env:ro
      - /BASE_PATH:/tvshows    