version: "3.8"

services:
  renamer-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: episode-renamer-backend
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3332:3332"
    volumes:
      - ./dependencies/.env:/app/dependencies/.env:ro
      - ./tvshows:/tvshows

  renamer-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: episode-renamer-frontend
    restart: unless-stopped

    ports:
      - "3000:3000"

    depends_on:
      - renamer-backend